### ISSUE TITLE
Error when connecting to mqtt broker using loopback adress

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [hvalev/dht22mqtt-homeassistant-docker#50]
Hi! When running the container with `-e broker=127.0.0.1` it returns an error:
```
Traceback (most recent call last):
  File "//dht22mqtt.py", line 216, in <module>
    client.connect(mqtt_brokeraddr, keepalive=dht22mqtt_refresh*60)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 914, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1044, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3685, in _create_socket_connection
    return socket.create_connection(addr, timeout=self._connect_timeout, source_address=source)
  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```
However, when running it with `-e broker=192.168.0.132` it works.

**Comment by hvalev** [comment]
Hi,
that is not surprising and also the intended use of the loopback interface, localhost and the local ip of your device. https://www.baeldung.com/linux/difference-ip-address has some information about those, but that is out of scope for this container as it is simply how networking works.

**Comment by Andrei-Iosifescu123** [comment]
> Hi, that is not surprising and also the intended use of the loopback interface, localhost and the local ip of your device. https://www.baeldung.com/linux/difference-ip-address has some information about those, but that is out of scope for this container as it is simply how networking works.

I don't get it. The MQTT broker runs on the same device as the container, so shouldn't I be able to connect to it using the loopback adress?

**Comment by hvalev** [comment]
I don't know what your setup is, but you're likely running docker on the bare metal with `network_mode: "host"` or `--net=host`. I guess it could work if you also run this container the same way, but simply localhost or 0.0.0.0 instead of the local network ip should suffice

**Comment by Andrei-Iosifescu123** [comment]
> I don't know what your setup is, but you're likely running home assistant on the bare metal or on docker with `network_mode: "host"` or `--net=host`. I guess it could work if you also run this container the same way, but simply localhost or 0.0.0.0 instead of the local network ip should suffice

Thanks, setting `--net=host` worked for me.
